### ISSUE TITLE
如果提供SDK的话这个实现不了多继承吧

### ISSUE THREAD

**Issue by nanfeifei** [brucevanfdm/ApplicationProxyDemo#1]
我理解的是给SDK使用者提供了一种继承多Applation的方案，需要SDK的使用者自己处理多个父类的情况，而不是不需要使用者继承父类Applation，不知道是不是我理解的不到位，不过还是赶紧作者提供了一种思路

**Comment by bruc3van** [comment]
是的，就像你说的：“需要SDK的使用者自己处理多个父类的情况”。SDK使用者可以参考这个多继承方案，解决用户在集成多个SDK并且他们都要求继承其Application的场景
